/**
 * The only place that talks to the backend.
 *
 * Every call resolves   none of these ever throw. A failed request comes back as
 * `{ error: "..." }` so callers render a friendly message instead of a blank screen.
 * That is the whole error strategy: the demo must never show a stack trace.
 *
 * `lang` is threaded through every call. The backend localises not just its error strings
 * but the scenario names, verdicts, alerts and month labels, because all of those are
 * generated by the simulation engine rather than by the UI.
 */

import { tr } from './strings'

const API_BASE = import.meta.env.VITE_API_BASE || ''
const TIMEOUT_MS = 45000

async function request(path, { lang = 'en', ...options } = {}) {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS)
  const url = path.startsWith('http') ? path : `${API_BASE}${path}`

  try {
    const response = await fetch(path, {
      headers: { 'Content-Type': 'application/json', 'Accept-Language': lang },
      signal: controller.signal,
      ...options,
    })

    // The backend returns its friendly message in `error` even on a 4xx/5xx, so parse
    // the body before deciding anything.
    let body
    try {
      body = await response.json()
    } catch {
      return { error: tr(lang, 'err.unreadable') }
    }

    if (!response.ok) {
      return { error: body?.error || tr(lang, 'err.status', { status: response.status }) }
    }
    return body
  } catch (err) {
    if (err.name === 'AbortError') {
      return { error: tr(lang, 'err.timeout') }
    }
    return { error: tr(lang, 'err.unreachable') }
  } finally {
    clearTimeout(timer)
  }
}

export const getProfile = (lang = 'en') => request(`/api/profile?lang=${lang}`, { lang })
export const getTimeline = (lang = 'en') => request(`/api/timeline?lang=${lang}`, { lang })
export const getHealth = (lang = 'en') => request(`/api/health?lang=${lang}`, { lang })

export const sendChat = (message, history, lang = 'en') =>
  request('/api/chat', {
    lang,
    method: 'POST',
    body: JSON.stringify({ message, history, lang }),
  })
