/**
 * The only place that talks to the backend.
 *
 * Every call resolves   none of these ever throw. A failed request comes back as
 * `{ error: "..." }` so callers render a friendly message instead of a blank screen.
 * That is the whole error strategy: the demo must never show a stack trace.
 *
 * `lang` is threaded through every call. The backend localises not just its error strings
 * but the scenario names, verdicts, alerts and month labels, because all of those are
 * generated by the simulation engine rather than by the UI.
 */

import { tr } from './strings'

const TIMEOUT_MS = 45000

async function request(path, { lang = 'en', ...options } = {}) {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS)

  try {
    const response = await fetch(path, {
      headers: { 'Content-Type': 'application/json', 'Accept-Language': lang },
      signal: controller.signal,
      ...options,
    })

    // The backend returns its friendly message in `error` even on a 4xx/5xx, so parse
    // the body before deciding anything.
    let body
    try {
      body = await response.json()
    } catch {
      return { error: tr(lang, 'err.unreadable') }
    }

    if (!response.ok) {
      return { error: body?.error || tr(lang, 'err.status', { status: response.status }) }
    }
    return body
  } catch (err) {
    if (err.name === 'AbortError') {
      return { error: tr(lang, 'err.timeout') }
    }
    return { error: tr(lang, 'err.unreachable') }
  } finally {
    clearTimeout(timer)
  }
}

export const getProfile = (lang = 'en') => request(`/api/profile?lang=${lang}`, { lang })
export const getTimeline = (lang = 'en') => request(`/api/timeline?lang=${lang}`, { lang })
export const getHealth = (lang = 'en') => request(`/api/health?lang=${lang}`, { lang })

export const sendChat = (message, history, lang = 'en') =>
  request('/api/chat', {
    lang,
    method: 'POST',
    body: JSON.stringify({ message, history, lang }),
  })

/**
 * Speech-to-text. Sends the recorded audio blob as multipart form data   we can't reuse
 * `request()` here because it hardcodes a JSON Content-Type, and the browser must set the
 * multipart boundary itself. Resolves to `{ text }` or `{ error }`, same contract as the
 * rest of this module. The timeout is generous because the first call also loads the model.
 */
export async function transcribeAudio(blob, lang = 'en') {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), 60000)
  try {
    const form = new FormData()
    form.append('audio', blob, 'speech.webm')
    const response = await fetch(`/api/transcribe?lang=${lang}`, {
      method: 'POST',
      headers: { 'Accept-Language': lang },
      body: form,
      signal: controller.signal,
    })
    let body
    try {
      body = await response.json()
    } catch {
      return { error: tr(lang, 'err.unreadable') }
    }
    if (!response.ok) {
      return { error: body?.error || tr(lang, 'err.status', { status: response.status }) }
    }
    return body
  } catch (err) {
    if (err.name === 'AbortError') return { error: tr(lang, 'err.timeout') }
    return { error: tr(lang, 'err.unreachable') }
  } finally {
    clearTimeout(timer)
  }
}
